"""Initial migration.

Revision ID: 26c4ec711b49
Revises: 
Create Date: 2024-12-06 16:13:35.809248

"""

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26c4ec711b49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellite_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("satellite_type", sa.String(length=64), nullable=False),
        sa.Column("src", sa.String(length=256), nullable=False),
        sa.Column("min", sa.Float(), nullable=False),
        sa.Column("max", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "annotation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_image_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("waste", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_image_id"],
            ["satellite_image.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.execute("DROP INDEX IF EXISTS idx_annotation_geom")
        batch_op.create_index("idx_annotation_geom", ["geom"], unique=False, postgresql_using="gist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.drop_index("idx_annotation_geom", postgresql_using="gist")

    op.drop_table("annotation")
    op.drop_table("user")
    op.drop_table("satellite_image")
    # ### end Alembic commands ###
