"""add unique constraint to satellite_image.filename

Revision ID: 7a7edb836370
Revises: 26c4ec711b49
Create Date: 2026-03-05 14:49:37.282546

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7a7edb836370"
down_revision = "26c4ec711b49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("satellite_image", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["filename"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("satellite_image", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
