"""Add admin user to User table.

Revision ID: bdc883c1e3d9
Revises: 26c4ec711b49
Create Date: 2024-12-06 16:18:59.627511

"""

from alembic import op
from flask_bcrypt import Bcrypt
import os
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bdc883c1e3d9"
down_revision = "26c4ec711b49"
branch_labels = None
depends_on = None


def generate_password_hash(password):
    # Generate password_hash with flask_bcrypt
    bcrypt = Bcrypt()
    return bcrypt.generate_password_hash(password).decode("utf-8")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Insert admin user into the "user" table
    admin_email = os.getenv("WD_ADMIN_EMAIL")
    admin_password_hash = generate_password_hash(os.getenv("WD_ADMIN_PASSWORD"))
    op.execute(
        f"""
        INSERT INTO public.user (name, email, password_hash, role)
        VALUES ('admin', '{admin_email}', '{admin_password_hash}', 'admin')
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove the admin user
    admin_email = os.getenv("WD_ADMIN_EMAIL")
    op.execute(f"DELETE FROM public.user WHERE name = 'admin' AND email = '{admin_email}'")

    # ### end Alembic commands ###
