"""Initial migration.

Revision ID: ea35b161eb13
Revises: 
Create Date: 2024-06-07 18:24:47.845213

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ea35b161eb13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellite_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("satellite_type", sa.String(length=64), nullable=False),
        sa.Column("src", sa.String(length=256), nullable=False),
        sa.Column("min", sa.Float(), nullable=False),
        sa.Column("max", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "annotation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_image_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("waste", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_image_id"],
            ["satellite_image.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.execute("DROP INDEX IF EXISTS idx_annotation_geom")
        batch_op.create_index("idx_annotation_geom", ["geom"], unique=False, postgresql_using="gist")

    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column("proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.CheckConstraint("(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.drop_index("idx_annotation_geom", postgresql_using="gist")

    op.drop_table("annotation")
    op.drop_table("user")
    op.drop_table("satellite_image")
    # ### end Alembic commands ###
